# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QXLAnKFWMKO5DmZqlamEcKe33-qGG7Iq
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# import plotly.graph_objects as go
# from datetime import datetime, timedelta
# from fpdf import FPDF
# import os
# from src.utils import *
# from src.viz import *
# 
# # --- SOPHISTICATED CSS ---
# st.markdown("""
# <style>
#     /* General App Styling */
#     .stApp { background-color: #0E1117; }
# 
#     /* WIDER SIDEBAR */
#     section[data-testid="stSidebar"] {
#         width: 400px !important; /* Increased width */
#     }
#     [data-testid="stSidebar"] {
#         background-color: #161B22;
#         border-right: 1px solid #30363D;
#     }
# 
#     /* Metrics */
#     [data-testid="metric-container"] {
#         background-color: #21262D;
#         border-left: 4px solid #DC143C;
#         padding: 10px 15px;
#         border-radius: 5px;
#         box-shadow: 0 2px 4px rgba(0,0,0,0.2);
#     }
#     [data-testid="stMetricValue"] { color: #E0E0E0 !important; font-weight: 600; }
#     [data-testid="stMetricLabel"] { color: #A0A0A0 !important; }
# 
#     /* Rudraksh Insight Box */
#     .insight-box {
#         background-color: #1F2937;
#         border: 1px solid #374151;
#         border-left: 5px solid #DC143C;
#         padding: 15px;
#         border-radius: 8px;
#         margin-bottom: 20px;
#         color: #E5E7EB;
#         font-family: 'Arial';
#     }
#     .insight-title {
#         color: #DC143C;
#         font-weight: bold;
#         margin-bottom: 8px;
#         font-size: 1.1em;
#     }
# 
#     /* Headers & Tabs */
#     h1, h2, h3 { font-family: 'Arial'; letter-spacing: -0.5px; color: #FFFFFF !important; }
#     .stTabs [data-baseweb="tab-list"] { gap: 8px; }
#     .stTabs [data-baseweb="tab"] {
#         background-color: #21262D;
#         border-radius: 4px;
#         color: #A0A0A0;
#         border: 1px solid #30363D;
#     }
#     .stTabs [aria-selected="true"] {
#         background-color: #DC143C !important;
#         color: #FFFFFF !important;
#         border: none;
#     }
# </style>
# """, unsafe_allow_html=True)
# 
# # --- PREMIUM PDF REPORT ---
# class QuantPDF(FPDF):
#     def header(self):
#         self.set_fill_color(22, 27, 34); self.rect(0, 0, 210, 35, 'F')
#         self.set_font('Arial', 'B', 22); self.set_text_color(220, 20, 60)
#         self.cell(0, 15, 'SECTORAL PERFORMANCE REPORT', 0, 1, 'L')
#         self.set_font('Arial', '', 10); self.set_text_color(150)
#         self.cell(0, 5, f'Generated by Professional Analyst Rudraksh | {datetime.today().strftime("%Y-%m-%d")}', 0, 1, 'L')
#         self.ln(20)
#     def footer(self):
#         self.set_y(-15); self.set_font('Arial', '', 8); self.set_text_color(100)
#         self.cell(0, 10, f'Page {self.page_no()} | CONFIDENTIAL', 0, 0, 'R')
# 
# def generate_pdf(metrics, meta, insights):
#     pdf = QuantPDF(); pdf.add_page()
# 
#     # Managerial Insights Box in PDF
#     pdf.set_fill_color(245, 245, 245); pdf.set_draw_color(220, 20, 60); pdf.set_line_width(0.5)
#     pdf.rect(10, 45, 190, 45, 'DF')
#     pdf.set_xy(15, 50); pdf.set_font('Arial', 'B', 12); pdf.set_text_color(220, 20, 60)
#     pdf.cell(0, 8, "MANAGERIAL INSIGHTS (BY RUDRAKSH)", 0, 1)
#     pdf.set_font('Arial', '', 10); pdf.set_text_color(50)
#     clean_insights = insights.replace('\n\n', '\n')
#     pdf.set_xy(15, 60); pdf.multi_cell(180, 5, clean_insights)
#     pdf.ln(15)
# 
#     # Metrics Table
#     pdf.set_font('Arial', 'B', 12); pdf.set_text_color(220, 20, 60)
#     pdf.cell(0, 10, "KEY QUANTITATIVE METRICS", 0, 1)
#     pdf.set_font('Arial', 'B', 9); pdf.set_fill_color(50); pdf.set_text_color(255)
#     cols = ['Ticker','Sharpe','Beta','Max DD']
#     for c in cols: pdf.cell(47, 8, c, 1, 0, 'C', 1)
#     pdf.ln(); pdf.set_font('Arial', '', 9); pdf.set_text_color(0)
#     for idx, row in metrics.iterrows():
#         pdf.cell(47, 8, idx, 1, 0, 'C')
#         pdf.cell(47, 8, f"{row['Sharpe Ratio']:.2f}", 1, 0, 'C')
#         pdf.cell(47, 8, f"{row['Beta']:.2f}", 1, 0, 'C')
#         pdf.cell(47, 8, f"{row['Max Drawdown']:.1%}", 1, 0, 'C')
#         pdf.ln()
# 
#     # Charts
#     pdf.add_page()
#     pdf.set_font('Arial', 'B', 12); pdf.set_text_color(220, 20, 60)
#     pdf.cell(0, 10, "APPENDIX: VISUAL ANALYSIS", 0, 1)
#     if os.path.exists('outputs/cum_ret.png'): pdf.image('outputs/cum_ret.png', x=10, y=30, w=190)
#     if os.path.exists('outputs/heatmap.png'): pdf.image('outputs/heatmap.png', x=10, y=140, w=100)
#     if os.path.exists('outputs/eff_frontier.png'): pdf.image('outputs/eff_frontier.png', x=110, y=140, w=90)
# 
#     pdf_path = "outputs/Sector_Report.pdf"
#     pdf.output(pdf_path)
#     return pdf_path
# 
# # --- MAIN DASHBOARD ---
# st.set_page_config(layout="wide", page_title="Sectoral Dashboard")
# st.title("Sectoral Performance & Correlation Dashboard")
# if 'tickers' not in st.session_state: st.session_state.tickers = ["NIFTY 50", "NIFTY BANK"]
# 
# # --- SIDEBAR WITH 10+ FILTERS ---
# with st.sidebar:
#     st.header("CUSTOMIZE YOUR ANALYSIS")
# 
#     # 1. Asset Universe
#     with st.expander("DISTINCT SECTORS / ASSETS", expanded=True):
#         choices = get_ticker_choices(); names = list(choices.keys())
#         for i in range(len(st.session_state.tickers)):
#             c1, c2 = st.columns([5, 1])
#             st.session_state.tickers[i] = c1.selectbox(f"Asset {i+1}", names, index=names.index(st.session_state.tickers[i]) if st.session_state.tickers[i] in names else 0, key=f"s_{i}", label_visibility="collapsed")
#             if c2.button("➖", key=f"rm_{i}") and len(st.session_state.tickers) > 1:
#                 st.session_state.tickers.pop(i); st.rerun()
#         if st.button("➕ Add Sector", use_container_width=True): st.session_state.tickers.append(names[0]); st.rerun()
#         custom = st.text_input("Or Custom Ticker (e.g. MSFT)")
#         if st.button("Add Custom") and custom: st.session_state.tickers.append(custom); st.rerun()
# 
#     # 2. Time Horizon
#     with st.expander("TIME HORIZON", expanded=True):
#         start_date = st.date_input("Start Date", datetime.today() - timedelta(days=365*2))
#         end_date = st.date_input("End Date", datetime.today())
# 
#     # 3. Benchmark & Frequency
#     with st.expander("DATA PARAMETERS"):
#         benchmark = st.selectbox("Benchmark Asset", names, index=names.index("NIFTY 50"))
#         freq = st.selectbox("Data Frequency", ["Daily", "Weekly", "Monthly"], index=0)
#         freq_map = {"Daily": "D", "Weekly": "W", "Monthly": "M"}
# 
#     # 4. Risk Parameters
#     with st.expander("RISK MODEL SETTINGS"):
#         rf_rate = st.slider("Risk-Free Rate (%)", 0.0, 10.0, 4.0, 0.5) / 100
#         var_conf = st.selectbox("VaR Confidence Level", [0.90, 0.95, 0.99], index=1)
#         roll_window = st.slider("Rolling Window (Days)", 30, 365, 60)
# 
#     # 5. Visualization Filters
#     with st.expander("CHART OVERLAYS"):
#         ma_overlay = st.multiselect("Technical Indicators", ["SMA 50", "SMA 200", "Bollinger Bands"])
#         show_bench = st.checkbox("Overlay Benchmark on Charts", value=True)
# 
#     if st.button("RUN ANALYSIS", type="primary", use_container_width=True):
#         with st.spinner("Executing Quant Engines..."):
#             mapped = [choices.get(t,t) for t in st.session_state.tickers]
#             bench_ticker = choices.get(benchmark, benchmark)
#             if bench_ticker not in mapped: mapped.append(bench_ticker)
# 
#             raw_px, src = get_prices(list(set(mapped)), start_date, end_date)
#             px_data = resample_data(raw_px, freq_map[freq])
#             metrics = compute_metrics(px_data, bench_ticker, rf_rate, var_conf)
#             sim = simulate_portfolio(px_data)
#             insights = generate_insights(metrics, benchmark)
# 
#             # Generate static assets
#             plot_cumulative(px_data); plot_drawdown(px_data)
#             plot_corr_heatmap(px_data); plot_efficient_frontier(sim)
# 
#             st.session_state.data = {
#                 'px': px_data, 'met': metrics, 'sim': sim, 'insights': insights,
#                 'meta': {'src': src, 'bench': benchmark, 'start': str(start_date), 'end': str(end_date), 'tickers': st.session_state.tickers}
#             }
#             st.rerun()
# 
# # --- MAIN BODY ---
# if 'data' in st.session_state:
#     d = st.session_state.data
# 
#     # MANAGERIAL INSIGHTS BOX
#     st.markdown(f"""
#     <div class="insight-box">
#         <div class="insight-title">ANALYST INSIGHTS (RUDRAKSH)</div>
#         {d['insights']}
#     </div>
#     """, unsafe_allow_html=True)
# 
#     # KPI ROW
#     k1, k2, k3, k4 = st.columns(4)
#     k1.metric("BENCHMARK", d['meta']['bench'])
#     k2.metric("TOP ASSET (SHARPE)", d['met']['Sharpe Ratio'].idxmax(), f"{d['met']['Sharpe Ratio'].max():.2f}")
#     k3.metric("HIGHEST RISK (VOL)", d['met']['Ann Volatility'].idxmax(), f"{d['met']['Ann Volatility'].max():.1%}")
#     k4.metric("DATA SOURCE", d['meta']['src'].upper(), delta="Live" if d['meta']['src']=='live' else "Offline Mode", delta_color="off")
# 
#     # TABS
#     t1, t2, t3, t4 = st.tabs(["📈 MARKET", "📉 RISK LAB", "⚖️ PORTFOLIO", "📄 REPORT"])
# 
#     with t1:
#         norm_px = d['px'] / d['px'].iloc[0]
#         fig = px.line(norm_px, title="RELATIVE PERFORMANCE (BASE=1.0)", color_discrete_sequence=px.colors.qualitative.Vivid)
#         fig.update_layout(template="plotly_dark", hovermode="x unified", paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')
#         st.plotly_chart(fig, use_container_width=True)
# 
#     with t2:
#         st.dataframe(d['met'].style.format("{:.2f}").background_gradient(cmap='RdBu', subset=['Sharpe Ratio', 'Beta']), use_container_width=True)
#         c1, c2 = st.columns(2)
#         with c1:
#             fig_dd = px.area((d['px']/d['px'].expanding().max())-1, title="DRAWDOWNS", template="plotly_dark")
#             st.plotly_chart(fig_dd, use_container_width=True)
#         with c2:
#             corr = d['px'].pct_change().corr()
#             fig_corr = px.imshow(corr, text_auto=".2f", title="CORRELATION HEATMAP", template="plotly_dark", color_continuous_scale='RdBu_r', zmin=-1, zmax=1)
#             st.plotly_chart(fig_corr, use_container_width=True)
# 
#     with t3:
#         fig_ef = px.scatter(d['sim'], x='Volatility', y='Return', color='Sharpe', title="EFFICIENT FRONTIER SIMULATION",
#                            template="plotly_dark", color_continuous_scale='magma')
#         st.plotly_chart(fig_ef, use_container_width=True)
# 
#     with t4:
#         st.write("Download the professional briefing document, including full charts and analyst commentary.")
#         if st.button("🖨️ GENERATE ANALYST REPORT PDF"):
#             with open(generate_pdf(d['met'], d['meta'], d['insights']), "rb") as f:
#                 st.download_button("DOWNLOAD PDF", f, "Sector_Report.pdf", "application/pdf", use_container_width=True)
# else:
#     st.info("Please configure your asset universe and click 'RUN ANALYSIS' in the sidebar to begin.")