# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QXLAnKFWMKO5DmZqlamEcKe33-qGG7Iq
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile src/viz.py
# import matplotlib.pyplot as plt
# import seaborn as sns
# import os
# import numpy as np
# 
# # --- SOPHISTICATED DARK THEME ---
# plt.style.use('dark_background')
# plt.rcParams.update({
#     'axes.facecolor': '#0E1117', 'savefig.facecolor': '#0E1117',
#     'figure.facecolor': '#0E1117', 'grid.color': '#262626',
#     'axes.edgecolor': '#333333', 'text.color': '#E0E0E0',
#     'axes.labelcolor': '#DC143C', 'xtick.color': '#A0A0A0',
#     'ytick.color': '#A0A0A0', 'figure.dpi': 150, 'axes.grid': True,
#     'grid.linestyle': '--', 'grid.alpha': 0.3, 'font.family': 'Arial'
# })
# 
# os.makedirs('outputs', exist_ok=True)
# 
# def plot_cumulative(prices, output_path='outputs/cum_ret.png'):
#     fig, ax = plt.subplots(figsize=(10, 5))
#     # Premium palette: Crimson, Slate, Teal, Gold, Indigo
#     colors = ['#DC143C', '#64748B', '#2DD4BF', '#D4AF37', '#818CF8']
#     ax.set_prop_cycle(color=colors)
#     (prices / prices.iloc[0]).plot(ax=ax, linewidth=2)
#     ax.set_title('CUMULATIVE PERFORMANCE (BASE=1.0)', fontweight='bold', pad=15, color='#E0E0E0')
#     ax.legend(frameon=False, labelcolor='linecolor')
#     plt.tight_layout(); plt.savefig(output_path); plt.close()
# 
# def plot_drawdown(prices, output_path='outputs/drawdown.png'):
#     fig, ax = plt.subplots(figsize=(10, 5))
#     cum = (1 + prices.pct_change()).cumprod()
#     running_max = cum.expanding().max()
#     dd = (cum / running_max) - 1
#     dd.plot(ax=ax, linewidth=1.5, alpha=0.8, cmap='flare')
#     ax.fill_between(dd.index, dd.min(axis=1), 0, color='#DC143C', alpha=0.1)
#     ax.set_title('UNDERWATER DRAWDOWN PROFILE', fontweight='bold', pad=15, color='#E0E0E0')
#     plt.tight_layout(); plt.savefig(output_path); plt.close()
# 
# def plot_corr_heatmap(prices, output_path='outputs/heatmap.png'):
#     fig, ax = plt.subplots(figsize=(8, 6))
#     # Sophisticated diverging map (Deep charcoal to Crimson)
#     cmap = sns.diverging_palette(220, 10, as_cmap=True)
#     sns.heatmap(prices.pct_change().corr(), annot=True, fmt=".2f",
#                 cmap=cmap, center=0, cbar=False, ax=ax, square=True,
#                 annot_kws={"size": 9, "weight": "bold"})
#     ax.set_title('CORRELATION MATRIX', fontweight='bold', pad=15, color='#E0E0E0')
#     plt.tight_layout(); plt.savefig(output_path); plt.close()
# 
# def plot_efficient_frontier(sim_results, output_path='outputs/eff_frontier.png'):
#     fig, ax = plt.subplots(figsize=(8, 6))
#     sc = ax.scatter(sim_results['Volatility'], sim_results['Return'],
#                     c=sim_results['Sharpe'], cmap='magma', s=15, alpha=0.6)
#     cbar = plt.colorbar(sc)
#     cbar.set_label('SHARPE RATIO', fontweight='bold', color='#DC143C')
#     ax.set_title('MEAN-VARIANCE FRONTIER', fontweight='bold', pad=15, color='#E0E0E0')
#     ax.set_xlabel('RISK (VOLATILITY)'); ax.set_ylabel('RETURN')
#     plt.tight_layout(); plt.savefig(output_path); plt.close()